### ISSUE TITLE
Support specifying artifact location

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contract-loader#18]
Support specifying artifact location.

Currently artifacts can only be in (or in sub-directory) of root `build` directory.

Raised by a community member in the forum wanting to use a specific directory structure in OpenZeppelin Test Environment:
https://forum.openzeppelin.com/t/contract-fromartifact-path-on-environment/2107

**Comment by vincentvanhassel** [comment]
Hi, i suggest to `function loadArtifact(contract, path) {
    if (path === void 0) { path = ''; } else { path += '/'  }
    var buildDir = find_up_1.default.sync(path + 'build', { type: 'directory' });
    if (!buildDir || !find_up_1.default.sync.exists(artifactsDir(buildDir))) {
        throw new Error('Could not find compiled artifacts directory');
    }
    return fs_extra_1.readJSONSync(artifactsDir(buildDir) + "/" + contract + ".json", { encoding: 'utf8' });
}`

**Comment by nventuro** [comment]
Hey @vincentvanhassel! I actually tackled this last Friday, just didn't get around to replying on the forum yet :)

The changes in Contract Loader are available on the latest version of Test Environmnet (v0.1.2): there's now a [`artifactsDir` option](https://docs.openzeppelin.com/test-environment/0.1/getting-started#configuration) you can use to specify a path.

**Comment by collect-code** [comment]
How can this work if `function dependencyArtifactPath()` still uses the hardcoded `build/contracts`.
I'm having a really bad time trying to import artifacts out of my project's folder...

Line 33 here:
https://github.com/OpenZeppelin/openzeppelin-contract-loader/blob/master/src/index.ts
