### ISSUE TITLE
eth_call fails due to a low default gas price

### ISSUE THREAD

**Issue by shark0der** [OpenZeppelin/openzeppelin-contract-loader#24]
The new `eth_call` implementation reverts when using a gas price lower than the block base fee. Using a gas price of `0` however does not revert and the checks are skipped. `setupLoader` defaults the `gasPrice` [to 1 gwei](https://github.com/OpenZeppelin/openzeppelin-contract-loader/blob/a5a8ef02dcd5c01ba6ed871f22e5914954b6f173/src/index.ts#L6) which as a consequence makes all calls to view functions revert.

This project doesn't seem to be actively maintained anymore so we're planning to switch to ethersjs in the near future but I thought I'd open this issue here for the reference.

**Comment by frangio** [comment]
Thanks for the report. Indeed this project is not being actively maintained so we're planning to release a fix for this issue and then deprecate the package. Sorry about the inconvenience!

**Comment by frangio** [comment]
I've removed the default gas price. Also added a notice in the readme about lack of active maintenance.
