### ISSUE TITLE
Loader requires both web3-eth-contract and truffle-contract dependencies to be present

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contract-loader#7]
The `setupLoader` method currently initializes both the truffle and web3 loader objects, which means that both dependencies need to be present. We should only require the one being requested by the user.

**Comment by frangio** [comment]
A quick fix is to use getters.

```typescript
return {
  get web3() {
    return web3Loader(provider, defaultSender, defaultGas);
  },
  ...
}
```
